## Support vector Machine

In [2]:
import numpy as nb
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
import joblib                                                                                           #To store the model

In [3]:
from sklearn.datasets import load_iris

In [4]:
data = load_iris()

In [5]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
pd.DataFrame(data.data , columns=data.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
df = pd.DataFrame(data.data , columns=data.feature_names)

In [8]:
data.target               # species 0--> setosa , 1--> versicolor , 2--> varginica 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df['target'] = data.target

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
df["Target_names"] = df['target'].map({i:name for i , name in enumerate(data.target_names)})                 # 0 , 1 ,2 ko uske target name se add kiya 

In [13]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target Target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

## Lets us perform the EDA Operations

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target Target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   Target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [16]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
Target_names         0
dtype: int64

## Lets us build the binary class by neglecting the one of the class 2 or else 

In [17]:
binary_df = df[df['target'] != 2]

In [18]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target Target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [19]:
x_binary = binary_df[['sepal length (cm)' ,'sepal width (cm)'	, 'petal length (cm)',	'petal width (cm)']]

In [20]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [21]:
y_binary = binary_df['target']

In [22]:
y_binary

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [23]:
x_train , x_test , y_train , y_test = train_test_split(x_binary , y_binary , test_size=0.2)

In [24]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.493750          3.093750           2.897500   
std             0.634722          0.489987           1.450183   
min             4.400000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.500000          3.050000           3.150000   
75%             5.900000          3.400000           4.400000   
max             7.000000          4.400000           5.000000   

       petal width (cm)  
count         80.000000  
mean           0.802500  
std            0.556884  
min            0.100000  
25%            0.200000  
50%            1.000000  
75%            1.300000  
max            1.800000

In [25]:
#Lets us standardise the data 
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [26]:
x_test = scaler.transform(x_test)

In [27]:
x_train

array([[ 0.00990896, -1.21941273,  0.76504528,  0.89899954],
       [ 0.00990896, -1.42478751,  0.5568697 ,  0.35688926],
       [ 0.1684523 , -1.21941273,  0.69565342,  0.53759269],
       [ 0.00990896,  2.27195846, -1.03914314, -1.08873813],
       [ 0.32699563, -0.39791363,  0.90382901,  0.89899954],
       [ 0.80262564, -1.83553706,  0.76504528,  0.35688926],
       [ 0.80262564,  0.62896025,  1.1120046 ,  1.44110981],
       [ 0.96116898, -0.39791363,  1.25078832,  1.07970296],
       [-0.46572105,  0.83433503, -0.96975128, -1.08873813],
       [ 1.912429  ,  0.01283592,  1.04261273,  1.07970296],
       [-0.78280773,  0.62896025, -0.90035942, -0.72733128],
       [ 0.32699563,  1.45045935, -0.83096755, -0.90803471],
       [-0.78280773,  0.83433503, -1.108535  , -0.90803471],
       [-1.0998944 , -0.19253885, -1.03914314, -0.90803471],
       [-0.78280773,  1.0397098 , -1.03914314, -1.08873813],
       [-1.57552441, -1.63016228, -1.108535  , -0.90803471],
       [-0.78280773,  0.

In [28]:
svm_binary = SVC(kernel='linear',C=1.0,probability=True)        

In [29]:
svm_binary.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [30]:
svm_binary.predict(x_test)

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1])

In [31]:
print("binary class classification reprt:\n" , classification_report(y_test,svm_binary.predict(x_test)))

binary class classification reprt:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [32]:
confusion_matrix(y_test,svm_binary.predict(x_test))

array([[11,  0],
       [ 0,  9]])

## Now we have to save the model in joblib 

In [33]:
joblib.dump(svm_binary , 'svm_binary.pkl')         # file name --> 'svm_binary.pkl'

['svm_binary.pkl']

## Lets do classification for multi class classification 0 , 1 , 2

In [34]:
x_multi = df[['sepal length (cm)' ,'sepal width (cm)'	, 'petal length (cm)',	'petal width (cm)']]

In [35]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [36]:
y_multi = df['target']

In [37]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [38]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi = train_test_split(x_multi , y_multi , test_size=0.2)

In [39]:
svm_multi = SVC(kernel='linear')

In [40]:
svm_multi.fit(x_train_multi , y_train_multi)

SVC(kernel='linear')

In [41]:
svm_multi.predict(x_test_multi)

array([0, 2, 1, 0, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2,
       0, 2, 0, 2, 2, 1, 0, 0])

In [42]:
print("report for multi class svc \n" , classification_report(y_test_multi , svm_multi.predict(x_test_multi)))

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [43]:
confusion_matrix(y_test_multi , svm_multi.predict(x_test_multi))

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]])

In [44]:
joblib.dump(svm_multi , 'svm_multi.pkl')
joblib.dump(scaler , 'scaler.pkl')

['scaler.pkl']

# Logistic Regression for binary class

In [45]:
#This is binary class data 
x_train , x_test , y_train , y_test

(array([[ 0.00990896, -1.21941273,  0.76504528,  0.89899954],
        [ 0.00990896, -1.42478751,  0.5568697 ,  0.35688926],
        [ 0.1684523 , -1.21941273,  0.69565342,  0.53759269],
        [ 0.00990896,  2.27195846, -1.03914314, -1.08873813],
        [ 0.32699563, -0.39791363,  0.90382901,  0.89899954],
        [ 0.80262564, -1.83553706,  0.76504528,  0.35688926],
        [ 0.80262564,  0.62896025,  1.1120046 ,  1.44110981],
        [ 0.96116898, -0.39791363,  1.25078832,  1.07970296],
        [-0.46572105,  0.83433503, -0.96975128, -1.08873813],
        [ 1.912429  ,  0.01283592,  1.04261273,  1.07970296],
        [-0.78280773,  0.62896025, -0.90035942, -0.72733128],
        [ 0.32699563,  1.45045935, -0.83096755, -0.90803471],
        [-0.78280773,  0.83433503, -1.108535  , -0.90803471],
        [-1.0998944 , -0.19253885, -1.03914314, -0.90803471],
        [-0.78280773,  1.0397098 , -1.03914314, -1.08873813],
        [-1.57552441, -1.63016228, -1.108535  , -0.90803471],
        

In [46]:
#this is multi class data 
x_train_multi , x_test_multi , y_train_multi , y_test_multi

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 110                6.5               3.2                5.1               2.0
 42                 4.4               3.2                1.3               0.2
 98                 5.1               2.5                3.0               1.1
 43                 5.0               3.5                1.6               0.6
 95                 5.7               3.0                4.2               1.2
 ..                 ...               ...                ...               ...
 108                6.7               2.5                5.8               1.8
 100                6.3               3.3                6.0               2.5
 99                 5.7               2.8                4.1               1.3
 130                7.4               2.8                6.1               1.9
 22                 4.6               3.6                1.0               0.2
 
 [120 rows x 4 columns],
      sepal length (cm)  

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
logistic_binary = LogisticRegression()
logistic_binary.fit(x_train , y_train)

LogisticRegression()

In [49]:
logistic_binary.predict(x_test)

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1])

In [50]:
print("classification report \n" , classification_report(y_test , logistic_binary.predict(x_test)))

classification report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [51]:
confusion_matrix(y_test , logistic_binary.predict(x_test))

array([[11,  0],
       [ 0,  9]])

In [52]:
joblib.dump(logistic_binary , "logistic_binary.pkl")

['logistic_binary.pkl']

# Logistic regression for multi class model 

In [53]:
from sklearn.multiclass import OneVsRestClassifier

### # Note --> here we do not use syntax like {LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)} instead we use  OneVsRestClassifier(LogisticRegression(solver='lbfgs',max_iter=2000)) coz new python version have The default behavior in modern scikit-learn which automatically handles multiclass problems

In [54]:
logistic_ovr = OneVsRestClassifier(LogisticRegression(solver='lbfgs',max_iter=2000))    

In [55]:
logistic_ovr.fit(x_train_multi , y_train_multi)

OneVsRestClassifier(estimator=LogisticRegression(max_iter=2000))

In [56]:
logistic_ovr.predict(x_test_multi)

array([0, 2, 1, 0, 0, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2,
       0, 2, 0, 2, 2, 2, 0, 0])

In [57]:
print("Classificatiob report for OVR logistics \n" , classification_report(y_test_multi ,logistic_ovr.predict(x_test_multi) ))

Classificatiob report for OVR logistics 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.75      0.86         8
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.92      0.92        30
weighted avg       0.94      0.93      0.93        30



In [58]:
confusion_matrix(y_test_multi ,logistic_ovr.predict(x_test_multi))

array([[12,  0,  0],
       [ 0,  6,  2],
       [ 0,  0, 10]])

In [59]:
joblib.dump(logistic_ovr , "logistic.pkl")

['logistic.pkl']